version: "3"
services:
  nginx:
      build:
        context: .
        dockerfile: ./docker/nginx.dockerfile
      container_name: nginx
      depends_on:
          - node1
          - node2
          - node3
      ports:
          - "80:80"
      networks:
        - production-network

  node1:
      build:
        context: .
        dockerfile: ./docker/node.dockerfile
      container_name: node1
      depends_on:
          - redis
      ports:
          - "8080"
      networks:
        - production-network

  node2:
      build:
          context: .
          dockerfile: "./docker/node.dockerfile"
      container_name: node2
      depends_on:
          - redis
      ports:
          - "8080"
      networks:
        - production-network

  node3:
      build:
        context: .
        dockerfile: ./docker/node.dockerfile
      container_name: node3
      depends_on:
          - redis
      ports:
          - "8080"
      networks:
        - production-network

  redis:
      image: redis
      ports:
          - "6379"
      networks:
        - production-network

networks: 
  production-network:
    driver: bridge